pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('notes-flashcards') {
                    sh 'npm install'
                }
            }
        }

        stage('Build App') {
            steps {
                dir('notes-flashcards') {
                    sh 'npm run build'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('notes-flashcards') {
                    sh 'docker build -t flashcards-app .'
                }
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker stop flashcards || true
                docker rm flashcards || true
                docker run -d --name flashcards -p 8081:80 flashcards-app
                '''
            }
        }
    }
}